### ISSUE TITLE
Problem when try to build production android 

### ISSUE THREAD

**Issue by togro** [melwinVincent/ionic4-star-rating#5]
All works fine on development enviroment or when i generate developer apk .

But when execute build production apk I receive this error :

ERROR in : Type StarRating in /Users/mtoro/GitHub/MGVideoReport/node_modules/ionic4-star-rating/dist/components/ionic4-star-rating-component.d.ts is part of the declarations of 2 modules: SharedStarRating in /Users/mtoro/GitHub/MGVideoReport/src/app/app.sharedrating.module.ts and StarRatingModule in /Users/mtoro/GitHub/MGVideoReport/node_modules/ionic4-star-rating/dist/ionic4-star-rating.module.d.ts! Please consider moving StarRating in /Users/mtoro/GitHub/MGVideoReport/node_modules/ionic4-star-rating/dist/components/ionic4-star-rating-component.d.ts to a higher module that imports SharedStarRating in /Users/mtoro/GitHub/MGVideoReport/src/app/app.sharedrating.module.ts and StarRatingModule in /Users/mtoro/GitHub/MGVideoReport/node_modules/ionic4-star-rating/dist/ionic4-star-rating.module.d.ts. You can also create a new NgModule that exports and includes StarRating in /Users/mtoro/GitHub/MGVideoReport/node_modules/ionic4-star-rating/dist/components/ionic4-star-rating-component.d.ts then import that NgModule in SharedStarRating in /Users/mtoro/GitHub/MGVideoReport/src/app/app.sharedrating.module.ts and StarRatingModule in /Users/mtoro/GitHub/MGVideoReport/node_modules/ionic4-star-rating/dist/ionic4-star-rating.module.d.ts.

[ERROR] An error occurred while running subprocess ng.

**Comment by togro** [comment]
On file index.d.ts from directory node_modules/ionic4-star-rating/dist have 2 lines :

```javascript
//export * from './ionic4-star-rating.module';
export * from './components/ionic4-star-rating-component';
```

I comment first and works fine the generation of APK with --prod .

I'dont know why , but works for me commet that line .

**Comment by melwinVincent** [comment]
@togro 
This is not the right solution.

I have fixed the issue and updated the package in npm.
Please download the latest 
`npm i ionic4-star-rating@1.1.1`

Please upgrade the component and confirm.

**Instead of using sharedmodule.ts, you may directly import StarRatingModule in parent-component.module.ts**

Please follow the latest docs.
I'm attaching the screenshot of  the relevant step here

![Capture](https://user-images.githubusercontent.com/12426903/67640937-404f1780-f917-11e9-8d20-7d1d938ca3d5.PNG)

**Comment by togro** [comment]
Thanks ! , now is working without that
