### ISSUE TITLE
Can we place any placeholder for the prefetch rating data from server?

### ISSUE THREAD

**Issue by aditbharadwaj** [melwinVincent/ionic4-star-rating#6]

**Comment by melwinVincent** [comment]
Please provide more details

**Comment by aditbharadwaj** [comment]
sorry i couldn't update the issue .. but now my problem is solved.
what i had was this 
![current](https://user-images.githubusercontent.com/6751554/67634795-5db7bd80-f8e6-11e9-987a-a43435a56857.PNG)
and as per my question was i wanted to set the rating value dynamically 
so i tried this 
![want](https://user-images.githubusercontent.com/6751554/67634822-8b046b80-f8e6-11e9-8114-df12b509a083.PNG)
and it worked.  :) i can fetch dynamic value from server to show stars as per requirement.
