### ISSUE TITLE
ngStyle issue

### ISSUE THREAD

**Issue by drimtim5390** [melwinVincent/ionic4-star-rating#7]
Hi, please consider fixing issues in StarRatingModule. I think it can be done adding importing CommonModule. When I try to just import StarRating component it works fine in development. But if I try to build this it throws exception saying to consider using SharedModule. I tried this but got the same error. Then I used StarRatingModule instead StarRating component then got ngStyle error. After importing CommonModule in StarRatingModule files it seems to work fine.

**Comment by melwinVincent** [comment]
Hello @drimtim5390  : 
Please import CommonModule to your parent component as explained in the docs
https://www.npmjs.com/package/ionic4-star-rating

**Comment by melwinVincent** [comment]
@drimtim5390 :
The issue has been fixed in the latest release
`npm i ionic4-star-rating@1.1.1`

Please upgrade the component and confirm.

Thanks,
Melwin Vincent C
