### ISSUE TITLE
Not displaying on latest version of Ionic - 5.4.4

### ISSUE THREAD

**Issue by colbytown** [melwinVincent/ionic4-star-rating#8]
I have installed this and tried everything to get it to work. There are no console errors or CLI errors.

In the inspector it shows this....
<
ionic4-star-rating _ngcontent-ayj-c5="" activecolor="#488aff" activeicon="star" defaultcolor="#f4f4f4" defaulticon="star-outline" fontsize="32px" readonly="false"></ionic4-star-rating
>
But nothing displays. What am I missing?

**Comment by melwinVincent** [comment]
Hi @colbytown :
Please import CommonModule to your parent component as explained in the docs
https://www.npmjs.com/package/ionic4-star-rating

**Comment by melwinVincent** [comment]
@colbytown : 

The issue has been fixed in the latest release
npm i ionic4-star-rating@1.1.1

Please upgrade the component and confirm.

Thanks,
Melwin Vincent C

**Comment by colbytown** [comment]
@melwinVincent still nothing displaying unfortunately. 

What information do you need me to provide to debug this issue?
